/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherStatisticsRouteImport } from './routes/teacher.statistics'
import { Route as TeacherSettingsRouteImport } from './routes/teacher.settings'
import { Route as TeacherRevenueRouteImport } from './routes/teacher.revenue'
import { Route as TeacherRatingsRouteImport } from './routes/teacher.ratings'
import { Route as TeacherQuestionBankRouteImport } from './routes/teacher.question-bank'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherNotificationsRouteImport } from './routes/teacher.notifications'
import { Route as TeacherCoursesRouteImport } from './routes/teacher.courses'
import { Route as TeacherCouponsRouteImport } from './routes/teacher.coupons'
import { Route as TeacherProfileTeacherIdRouteImport } from './routes/teacher-profile.$teacherId'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminTeachersRouteImport } from './routes/super-admin.teachers'
import { Route as SuperAdminStudentsRouteImport } from './routes/super-admin.students'
import { Route as SuperAdminSimulationLogsRouteImport } from './routes/super-admin.simulation-logs'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminSecurityRouteImport } from './routes/super-admin.security'
import { Route as SuperAdminReputationRouteImport } from './routes/super-admin.reputation'
import { Route as SuperAdminReportsRouteImport } from './routes/super-admin.reports'
import { Route as SuperAdminPaymentsRouteImport } from './routes/super-admin.payments'
import { Route as SuperAdminOperationsRouteImport } from './routes/super-admin.operations'
import { Route as SuperAdminNotificationsRouteImport } from './routes/super-admin.notifications'
import { Route as SuperAdminCoursesRouteImport } from './routes/super-admin.courses'
import { Route as SuperAdminBrandingRouteImport } from './routes/super-admin.branding'
import { Route as SuperAdminBackupRouteImport } from './routes/super-admin.backup'
import { Route as SuperAdminAuditLogsRouteImport } from './routes/super-admin.audit-logs'
import { Route as SuperAdminAnalyticsRouteImport } from './routes/super-admin.analytics'
import { Route as SuperAdminAiRouteImport } from './routes/super-admin.ai'
import { Route as SuperAdminAdminsRouteImport } from './routes/super-admin.admins'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as AppTermsRouteImport } from './routes/app.terms'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPrivacyRouteImport } from './routes/app.privacy'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppMyCoursesRouteImport } from './routes/app.my-courses'
import { Route as AppInstructorsRouteImport } from './routes/app.instructors'
import { Route as AppHomeworkRouteImport } from './routes/app.homework'
import { Route as AppExamsRouteImport } from './routes/app.exams'
import { Route as AppDownloadsRouteImport } from './routes/app.downloads'
import { Route as AppCoursesRouteImport } from './routes/app.courses'
import { Route as AppAboutRouteImport } from './routes/app.about'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as TeacherLiveSessionIdRouteImport } from './routes/teacher.live.$sessionId'
import { Route as AppLiveSessionIdRouteImport } from './routes/app.live.$sessionId'
import { Route as AppInstructorsInstructorIdRouteImport } from './routes/app.instructors.$instructorId'
import { Route as AppDownloadsPlayerRouteImport } from './routes/app.downloads.player'
import { Route as AppCoursesCourseIdRouteImport } from './routes/app.courses.$courseId'
import { Route as ApiPlayerVerifyDeviceRouteImport } from './routes/api.player.verify-device'
import { Route as ApiPlayerProgressRouteImport } from './routes/api.player.progress'
import { Route as ApiPlayerLogSecurityEventRouteImport } from './routes/api.player.log-security-event'
import { Route as ApiPlayerGetVideoUrlRouteImport } from './routes/api.player.get-video-url'
import { Route as ApiPlayerCoursesRouteImport } from './routes/api.player.courses'
import { Route as ApiPlayerAuthRouteImport } from './routes/api.player.auth'
import { Route as ApiPlayerOpenLessonIdRouteImport } from './routes/api.player.open-lesson.$id'
import { Route as ApiPlayerCourseIdRouteImport } from './routes/api.player.course.$id'
import { Route as ApiPlayerAuthProfileRouteImport } from './routes/api.player.auth.profile'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherStatisticsRoute = TeacherStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherRevenueRoute = TeacherRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherRatingsRoute = TeacherRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherQuestionBankRoute = TeacherQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotificationsRoute = TeacherNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCoursesRoute = TeacherCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCouponsRoute = TeacherCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileTeacherIdRoute = TeacherProfileTeacherIdRouteImport.update({
  id: '/teacher-profile/$teacherId',
  path: '/teacher-profile/$teacherId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminTeachersRoute = SuperAdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminStudentsRoute = SuperAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSimulationLogsRoute =
  SuperAdminSimulationLogsRouteImport.update({
    id: '/simulation-logs',
    path: '/simulation-logs',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSecurityRoute = SuperAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminReputationRoute = SuperAdminReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminReportsRoute = SuperAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPaymentsRoute = SuperAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminOperationsRoute = SuperAdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminNotificationsRoute = SuperAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminCoursesRoute = SuperAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminBrandingRoute = SuperAdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminBackupRoute = SuperAdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAuditLogsRoute = SuperAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAnalyticsRoute = SuperAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAiRoute = SuperAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAdminsRoute = SuperAdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SuperAdminRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMyCoursesRoute = AppMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => AppRoute,
} as any)
const AppInstructorsRoute = AppInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeworkRoute = AppHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsRoute = AppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherLiveSessionIdRoute = TeacherLiveSessionIdRouteImport.update({
  id: '/live/$sessionId',
  path: '/live/$sessionId',
  getParentRoute: () => TeacherRoute,
} as any)
const AppLiveSessionIdRoute = AppLiveSessionIdRouteImport.update({
  id: '/live/$sessionId',
  path: '/live/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppInstructorsInstructorIdRoute =
  AppInstructorsInstructorIdRouteImport.update({
    id: '/$instructorId',
    path: '/$instructorId',
    getParentRoute: () => AppInstructorsRoute,
  } as any)
const AppDownloadsPlayerRoute = AppDownloadsPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => AppDownloadsRoute,
} as any)
const AppCoursesCourseIdRoute = AppCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppCoursesRoute,
} as any)
const ApiPlayerVerifyDeviceRoute = ApiPlayerVerifyDeviceRouteImport.update({
  id: '/api/player/verify-device',
  path: '/api/player/verify-device',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerProgressRoute = ApiPlayerProgressRouteImport.update({
  id: '/api/player/progress',
  path: '/api/player/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerLogSecurityEventRoute =
  ApiPlayerLogSecurityEventRouteImport.update({
    id: '/api/player/log-security-event',
    path: '/api/player/log-security-event',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlayerGetVideoUrlRoute = ApiPlayerGetVideoUrlRouteImport.update({
  id: '/api/player/get-video-url',
  path: '/api/player/get-video-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerCoursesRoute = ApiPlayerCoursesRouteImport.update({
  id: '/api/player/courses',
  path: '/api/player/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerAuthRoute = ApiPlayerAuthRouteImport.update({
  id: '/api/player/auth',
  path: '/api/player/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerOpenLessonIdRoute = ApiPlayerOpenLessonIdRouteImport.update({
  id: '/api/player/open-lesson/$id',
  path: '/api/player/open-lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerCourseIdRoute = ApiPlayerCourseIdRouteImport.update({
  id: '/api/player/course/$id',
  path: '/api/player/course/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerAuthProfileRoute = ApiPlayerAuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ApiPlayerAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/support': typeof SupportRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/app/about': typeof AppAboutRoute
  '/app/courses': typeof AppCoursesRouteWithChildren
  '/app/downloads': typeof AppDownloadsRouteWithChildren
  '/app/exams': typeof AppExamsRoute
  '/app/homework': typeof AppHomeworkRoute
  '/app/instructors': typeof AppInstructorsRouteWithChildren
  '/app/my-courses': typeof AppMyCoursesRoute
  '/app/notes': typeof AppNotesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/support': typeof AppSupportRoute
  '/app/terms': typeof AppTermsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/wallet': typeof AppWalletRoute
  '/super-admin/admins': typeof SuperAdminAdminsRoute
  '/super-admin/ai': typeof SuperAdminAiRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/audit-logs': typeof SuperAdminAuditLogsRoute
  '/super-admin/backup': typeof SuperAdminBackupRoute
  '/super-admin/branding': typeof SuperAdminBrandingRoute
  '/super-admin/courses': typeof SuperAdminCoursesRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/operations': typeof SuperAdminOperationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/reputation': typeof SuperAdminReputationRoute
  '/super-admin/security': typeof SuperAdminSecurityRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/simulation-logs': typeof SuperAdminSimulationLogsRoute
  '/super-admin/students': typeof SuperAdminStudentsRoute
  '/super-admin/teachers': typeof SuperAdminTeachersRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/teacher-profile/$teacherId': typeof TeacherProfileTeacherIdRoute
  '/teacher/coupons': typeof TeacherCouponsRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/ratings': typeof TeacherRatingsRoute
  '/teacher/revenue': typeof TeacherRevenueRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/statistics': typeof TeacherStatisticsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/api/player/auth': typeof ApiPlayerAuthRouteWithChildren
  '/api/player/courses': typeof ApiPlayerCoursesRoute
  '/api/player/get-video-url': typeof ApiPlayerGetVideoUrlRoute
  '/api/player/log-security-event': typeof ApiPlayerLogSecurityEventRoute
  '/api/player/progress': typeof ApiPlayerProgressRoute
  '/api/player/verify-device': typeof ApiPlayerVerifyDeviceRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/app/downloads/player': typeof AppDownloadsPlayerRoute
  '/app/instructors/$instructorId': typeof AppInstructorsInstructorIdRoute
  '/app/live/$sessionId': typeof AppLiveSessionIdRoute
  '/teacher/live/$sessionId': typeof TeacherLiveSessionIdRoute
  '/api/player/auth/profile': typeof ApiPlayerAuthProfileRoute
  '/api/player/course/$id': typeof ApiPlayerCourseIdRoute
  '/api/player/open-lesson/$id': typeof ApiPlayerOpenLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/app/about': typeof AppAboutRoute
  '/app/courses': typeof AppCoursesRouteWithChildren
  '/app/downloads': typeof AppDownloadsRouteWithChildren
  '/app/exams': typeof AppExamsRoute
  '/app/homework': typeof AppHomeworkRoute
  '/app/instructors': typeof AppInstructorsRouteWithChildren
  '/app/my-courses': typeof AppMyCoursesRoute
  '/app/notes': typeof AppNotesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/support': typeof AppSupportRoute
  '/app/terms': typeof AppTermsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/wallet': typeof AppWalletRoute
  '/super-admin/admins': typeof SuperAdminAdminsRoute
  '/super-admin/ai': typeof SuperAdminAiRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/audit-logs': typeof SuperAdminAuditLogsRoute
  '/super-admin/backup': typeof SuperAdminBackupRoute
  '/super-admin/branding': typeof SuperAdminBrandingRoute
  '/super-admin/courses': typeof SuperAdminCoursesRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/operations': typeof SuperAdminOperationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/reputation': typeof SuperAdminReputationRoute
  '/super-admin/security': typeof SuperAdminSecurityRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/simulation-logs': typeof SuperAdminSimulationLogsRoute
  '/super-admin/students': typeof SuperAdminStudentsRoute
  '/super-admin/teachers': typeof SuperAdminTeachersRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/teacher-profile/$teacherId': typeof TeacherProfileTeacherIdRoute
  '/teacher/coupons': typeof TeacherCouponsRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/ratings': typeof TeacherRatingsRoute
  '/teacher/revenue': typeof TeacherRevenueRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/statistics': typeof TeacherStatisticsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/api/player/auth': typeof ApiPlayerAuthRouteWithChildren
  '/api/player/courses': typeof ApiPlayerCoursesRoute
  '/api/player/get-video-url': typeof ApiPlayerGetVideoUrlRoute
  '/api/player/log-security-event': typeof ApiPlayerLogSecurityEventRoute
  '/api/player/progress': typeof ApiPlayerProgressRoute
  '/api/player/verify-device': typeof ApiPlayerVerifyDeviceRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/app/downloads/player': typeof AppDownloadsPlayerRoute
  '/app/instructors/$instructorId': typeof AppInstructorsInstructorIdRoute
  '/app/live/$sessionId': typeof AppLiveSessionIdRoute
  '/teacher/live/$sessionId': typeof TeacherLiveSessionIdRoute
  '/api/player/auth/profile': typeof ApiPlayerAuthProfileRoute
  '/api/player/course/$id': typeof ApiPlayerCourseIdRoute
  '/api/player/open-lesson/$id': typeof ApiPlayerOpenLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/support': typeof SupportRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/app/about': typeof AppAboutRoute
  '/app/courses': typeof AppCoursesRouteWithChildren
  '/app/downloads': typeof AppDownloadsRouteWithChildren
  '/app/exams': typeof AppExamsRoute
  '/app/homework': typeof AppHomeworkRoute
  '/app/instructors': typeof AppInstructorsRouteWithChildren
  '/app/my-courses': typeof AppMyCoursesRoute
  '/app/notes': typeof AppNotesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/support': typeof AppSupportRoute
  '/app/terms': typeof AppTermsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/wallet': typeof AppWalletRoute
  '/super-admin/admins': typeof SuperAdminAdminsRoute
  '/super-admin/ai': typeof SuperAdminAiRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/audit-logs': typeof SuperAdminAuditLogsRoute
  '/super-admin/backup': typeof SuperAdminBackupRoute
  '/super-admin/branding': typeof SuperAdminBrandingRoute
  '/super-admin/courses': typeof SuperAdminCoursesRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/operations': typeof SuperAdminOperationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/reputation': typeof SuperAdminReputationRoute
  '/super-admin/security': typeof SuperAdminSecurityRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/simulation-logs': typeof SuperAdminSimulationLogsRoute
  '/super-admin/students': typeof SuperAdminStudentsRoute
  '/super-admin/teachers': typeof SuperAdminTeachersRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/teacher-profile/$teacherId': typeof TeacherProfileTeacherIdRoute
  '/teacher/coupons': typeof TeacherCouponsRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/ratings': typeof TeacherRatingsRoute
  '/teacher/revenue': typeof TeacherRevenueRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/statistics': typeof TeacherStatisticsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/api/player/auth': typeof ApiPlayerAuthRouteWithChildren
  '/api/player/courses': typeof ApiPlayerCoursesRoute
  '/api/player/get-video-url': typeof ApiPlayerGetVideoUrlRoute
  '/api/player/log-security-event': typeof ApiPlayerLogSecurityEventRoute
  '/api/player/progress': typeof ApiPlayerProgressRoute
  '/api/player/verify-device': typeof ApiPlayerVerifyDeviceRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/app/downloads/player': typeof AppDownloadsPlayerRoute
  '/app/instructors/$instructorId': typeof AppInstructorsInstructorIdRoute
  '/app/live/$sessionId': typeof AppLiveSessionIdRoute
  '/teacher/live/$sessionId': typeof TeacherLiveSessionIdRoute
  '/api/player/auth/profile': typeof ApiPlayerAuthProfileRoute
  '/api/player/course/$id': typeof ApiPlayerCourseIdRoute
  '/api/player/open-lesson/$id': typeof ApiPlayerOpenLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/login'
    | '/privacy'
    | '/register'
    | '/super-admin'
    | '/support'
    | '/teacher'
    | '/terms'
    | '/admin/certificates'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/teachers'
    | '/app/about'
    | '/app/courses'
    | '/app/downloads'
    | '/app/exams'
    | '/app/homework'
    | '/app/instructors'
    | '/app/my-courses'
    | '/app/notes'
    | '/app/notifications'
    | '/app/privacy'
    | '/app/profile'
    | '/app/support'
    | '/app/terms'
    | '/app/timeline'
    | '/app/wallet'
    | '/super-admin/admins'
    | '/super-admin/ai'
    | '/super-admin/analytics'
    | '/super-admin/audit-logs'
    | '/super-admin/backup'
    | '/super-admin/branding'
    | '/super-admin/courses'
    | '/super-admin/notifications'
    | '/super-admin/operations'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/reputation'
    | '/super-admin/security'
    | '/super-admin/settings'
    | '/super-admin/simulation-logs'
    | '/super-admin/students'
    | '/super-admin/teachers'
    | '/super-admin/users'
    | '/teacher-profile/$teacherId'
    | '/teacher/coupons'
    | '/teacher/courses'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/question-bank'
    | '/teacher/ratings'
    | '/teacher/revenue'
    | '/teacher/settings'
    | '/teacher/statistics'
    | '/teacher/students'
    | '/admin/'
    | '/app/'
    | '/super-admin/'
    | '/teacher/'
    | '/api/player/auth'
    | '/api/player/courses'
    | '/api/player/get-video-url'
    | '/api/player/log-security-event'
    | '/api/player/progress'
    | '/api/player/verify-device'
    | '/app/courses/$courseId'
    | '/app/downloads/player'
    | '/app/instructors/$instructorId'
    | '/app/live/$sessionId'
    | '/teacher/live/$sessionId'
    | '/api/player/auth/profile'
    | '/api/player/course/$id'
    | '/api/player/open-lesson/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/admin/certificates'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/teachers'
    | '/app/about'
    | '/app/courses'
    | '/app/downloads'
    | '/app/exams'
    | '/app/homework'
    | '/app/instructors'
    | '/app/my-courses'
    | '/app/notes'
    | '/app/notifications'
    | '/app/privacy'
    | '/app/profile'
    | '/app/support'
    | '/app/terms'
    | '/app/timeline'
    | '/app/wallet'
    | '/super-admin/admins'
    | '/super-admin/ai'
    | '/super-admin/analytics'
    | '/super-admin/audit-logs'
    | '/super-admin/backup'
    | '/super-admin/branding'
    | '/super-admin/courses'
    | '/super-admin/notifications'
    | '/super-admin/operations'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/reputation'
    | '/super-admin/security'
    | '/super-admin/settings'
    | '/super-admin/simulation-logs'
    | '/super-admin/students'
    | '/super-admin/teachers'
    | '/super-admin/users'
    | '/teacher-profile/$teacherId'
    | '/teacher/coupons'
    | '/teacher/courses'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/question-bank'
    | '/teacher/ratings'
    | '/teacher/revenue'
    | '/teacher/settings'
    | '/teacher/statistics'
    | '/teacher/students'
    | '/admin'
    | '/app'
    | '/super-admin'
    | '/teacher'
    | '/api/player/auth'
    | '/api/player/courses'
    | '/api/player/get-video-url'
    | '/api/player/log-security-event'
    | '/api/player/progress'
    | '/api/player/verify-device'
    | '/app/courses/$courseId'
    | '/app/downloads/player'
    | '/app/instructors/$instructorId'
    | '/app/live/$sessionId'
    | '/teacher/live/$sessionId'
    | '/api/player/auth/profile'
    | '/api/player/course/$id'
    | '/api/player/open-lesson/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/login'
    | '/privacy'
    | '/register'
    | '/super-admin'
    | '/support'
    | '/teacher'
    | '/terms'
    | '/admin/certificates'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/teachers'
    | '/app/about'
    | '/app/courses'
    | '/app/downloads'
    | '/app/exams'
    | '/app/homework'
    | '/app/instructors'
    | '/app/my-courses'
    | '/app/notes'
    | '/app/notifications'
    | '/app/privacy'
    | '/app/profile'
    | '/app/support'
    | '/app/terms'
    | '/app/timeline'
    | '/app/wallet'
    | '/super-admin/admins'
    | '/super-admin/ai'
    | '/super-admin/analytics'
    | '/super-admin/audit-logs'
    | '/super-admin/backup'
    | '/super-admin/branding'
    | '/super-admin/courses'
    | '/super-admin/notifications'
    | '/super-admin/operations'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/reputation'
    | '/super-admin/security'
    | '/super-admin/settings'
    | '/super-admin/simulation-logs'
    | '/super-admin/students'
    | '/super-admin/teachers'
    | '/super-admin/users'
    | '/teacher-profile/$teacherId'
    | '/teacher/coupons'
    | '/teacher/courses'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/question-bank'
    | '/teacher/ratings'
    | '/teacher/revenue'
    | '/teacher/settings'
    | '/teacher/statistics'
    | '/teacher/students'
    | '/admin/'
    | '/app/'
    | '/super-admin/'
    | '/teacher/'
    | '/api/player/auth'
    | '/api/player/courses'
    | '/api/player/get-video-url'
    | '/api/player/log-security-event'
    | '/api/player/progress'
    | '/api/player/verify-device'
    | '/app/courses/$courseId'
    | '/app/downloads/player'
    | '/app/instructors/$instructorId'
    | '/app/live/$sessionId'
    | '/teacher/live/$sessionId'
    | '/api/player/auth/profile'
    | '/api/player/course/$id'
    | '/api/player/open-lesson/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  SupportRoute: typeof SupportRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  TermsRoute: typeof TermsRoute
  TeacherProfileTeacherIdRoute: typeof TeacherProfileTeacherIdRoute
  ApiPlayerAuthRoute: typeof ApiPlayerAuthRouteWithChildren
  ApiPlayerCoursesRoute: typeof ApiPlayerCoursesRoute
  ApiPlayerGetVideoUrlRoute: typeof ApiPlayerGetVideoUrlRoute
  ApiPlayerLogSecurityEventRoute: typeof ApiPlayerLogSecurityEventRoute
  ApiPlayerProgressRoute: typeof ApiPlayerProgressRoute
  ApiPlayerVerifyDeviceRoute: typeof ApiPlayerVerifyDeviceRoute
  ApiPlayerCourseIdRoute: typeof ApiPlayerCourseIdRoute
  ApiPlayerOpenLessonIdRoute: typeof ApiPlayerOpenLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/statistics': {
      id: '/teacher/statistics'
      path: '/statistics'
      fullPath: '/teacher/statistics'
      preLoaderRoute: typeof TeacherStatisticsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/revenue': {
      id: '/teacher/revenue'
      path: '/revenue'
      fullPath: '/teacher/revenue'
      preLoaderRoute: typeof TeacherRevenueRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/ratings': {
      id: '/teacher/ratings'
      path: '/ratings'
      fullPath: '/teacher/ratings'
      preLoaderRoute: typeof TeacherRatingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/question-bank': {
      id: '/teacher/question-bank'
      path: '/question-bank'
      fullPath: '/teacher/question-bank'
      preLoaderRoute: typeof TeacherQuestionBankRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notifications': {
      id: '/teacher/notifications'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/courses': {
      id: '/teacher/courses'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherCoursesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/coupons': {
      id: '/teacher/coupons'
      path: '/coupons'
      fullPath: '/teacher/coupons'
      preLoaderRoute: typeof TeacherCouponsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher-profile/$teacherId': {
      id: '/teacher-profile/$teacherId'
      path: '/teacher-profile/$teacherId'
      fullPath: '/teacher-profile/$teacherId'
      preLoaderRoute: typeof TeacherProfileTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/teachers': {
      id: '/super-admin/teachers'
      path: '/teachers'
      fullPath: '/super-admin/teachers'
      preLoaderRoute: typeof SuperAdminTeachersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/students': {
      id: '/super-admin/students'
      path: '/students'
      fullPath: '/super-admin/students'
      preLoaderRoute: typeof SuperAdminStudentsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/simulation-logs': {
      id: '/super-admin/simulation-logs'
      path: '/simulation-logs'
      fullPath: '/super-admin/simulation-logs'
      preLoaderRoute: typeof SuperAdminSimulationLogsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/security': {
      id: '/super-admin/security'
      path: '/security'
      fullPath: '/super-admin/security'
      preLoaderRoute: typeof SuperAdminSecurityRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/reputation': {
      id: '/super-admin/reputation'
      path: '/reputation'
      fullPath: '/super-admin/reputation'
      preLoaderRoute: typeof SuperAdminReputationRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/reports': {
      id: '/super-admin/reports'
      path: '/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof SuperAdminReportsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/payments': {
      id: '/super-admin/payments'
      path: '/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof SuperAdminPaymentsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/operations': {
      id: '/super-admin/operations'
      path: '/operations'
      fullPath: '/super-admin/operations'
      preLoaderRoute: typeof SuperAdminOperationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/notifications': {
      id: '/super-admin/notifications'
      path: '/notifications'
      fullPath: '/super-admin/notifications'
      preLoaderRoute: typeof SuperAdminNotificationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/courses': {
      id: '/super-admin/courses'
      path: '/courses'
      fullPath: '/super-admin/courses'
      preLoaderRoute: typeof SuperAdminCoursesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/branding': {
      id: '/super-admin/branding'
      path: '/branding'
      fullPath: '/super-admin/branding'
      preLoaderRoute: typeof SuperAdminBrandingRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/backup': {
      id: '/super-admin/backup'
      path: '/backup'
      fullPath: '/super-admin/backup'
      preLoaderRoute: typeof SuperAdminBackupRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/audit-logs': {
      id: '/super-admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/super-admin/audit-logs'
      preLoaderRoute: typeof SuperAdminAuditLogsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/analytics': {
      id: '/super-admin/analytics'
      path: '/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof SuperAdminAnalyticsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/ai': {
      id: '/super-admin/ai'
      path: '/ai'
      fullPath: '/super-admin/ai'
      preLoaderRoute: typeof SuperAdminAiRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/admins': {
      id: '/super-admin/admins'
      path: '/admins'
      fullPath: '/super-admin/admins'
      preLoaderRoute: typeof SuperAdminAdminsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/terms': {
      id: '/app/terms'
      path: '/terms'
      fullPath: '/app/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/privacy': {
      id: '/app/privacy'
      path: '/privacy'
      fullPath: '/app/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-courses': {
      id: '/app/my-courses'
      path: '/my-courses'
      fullPath: '/app/my-courses'
      preLoaderRoute: typeof AppMyCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/instructors': {
      id: '/app/instructors'
      path: '/instructors'
      fullPath: '/app/instructors'
      preLoaderRoute: typeof AppInstructorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/homework': {
      id: '/app/homework'
      path: '/homework'
      fullPath: '/app/homework'
      preLoaderRoute: typeof AppHomeworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exams': {
      id: '/app/exams'
      path: '/exams'
      fullPath: '/app/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/downloads': {
      id: '/app/downloads'
      path: '/downloads'
      fullPath: '/app/downloads'
      preLoaderRoute: typeof AppDownloadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses': {
      id: '/app/courses'
      path: '/courses'
      fullPath: '/app/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/live/$sessionId': {
      id: '/teacher/live/$sessionId'
      path: '/live/$sessionId'
      fullPath: '/teacher/live/$sessionId'
      preLoaderRoute: typeof TeacherLiveSessionIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/app/live/$sessionId': {
      id: '/app/live/$sessionId'
      path: '/live/$sessionId'
      fullPath: '/app/live/$sessionId'
      preLoaderRoute: typeof AppLiveSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/instructors/$instructorId': {
      id: '/app/instructors/$instructorId'
      path: '/$instructorId'
      fullPath: '/app/instructors/$instructorId'
      preLoaderRoute: typeof AppInstructorsInstructorIdRouteImport
      parentRoute: typeof AppInstructorsRoute
    }
    '/app/downloads/player': {
      id: '/app/downloads/player'
      path: '/player'
      fullPath: '/app/downloads/player'
      preLoaderRoute: typeof AppDownloadsPlayerRouteImport
      parentRoute: typeof AppDownloadsRoute
    }
    '/app/courses/$courseId': {
      id: '/app/courses/$courseId'
      path: '/$courseId'
      fullPath: '/app/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/api/player/verify-device': {
      id: '/api/player/verify-device'
      path: '/api/player/verify-device'
      fullPath: '/api/player/verify-device'
      preLoaderRoute: typeof ApiPlayerVerifyDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/progress': {
      id: '/api/player/progress'
      path: '/api/player/progress'
      fullPath: '/api/player/progress'
      preLoaderRoute: typeof ApiPlayerProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/log-security-event': {
      id: '/api/player/log-security-event'
      path: '/api/player/log-security-event'
      fullPath: '/api/player/log-security-event'
      preLoaderRoute: typeof ApiPlayerLogSecurityEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/get-video-url': {
      id: '/api/player/get-video-url'
      path: '/api/player/get-video-url'
      fullPath: '/api/player/get-video-url'
      preLoaderRoute: typeof ApiPlayerGetVideoUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/courses': {
      id: '/api/player/courses'
      path: '/api/player/courses'
      fullPath: '/api/player/courses'
      preLoaderRoute: typeof ApiPlayerCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/auth': {
      id: '/api/player/auth'
      path: '/api/player/auth'
      fullPath: '/api/player/auth'
      preLoaderRoute: typeof ApiPlayerAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/open-lesson/$id': {
      id: '/api/player/open-lesson/$id'
      path: '/api/player/open-lesson/$id'
      fullPath: '/api/player/open-lesson/$id'
      preLoaderRoute: typeof ApiPlayerOpenLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/course/$id': {
      id: '/api/player/course/$id'
      path: '/api/player/course/$id'
      fullPath: '/api/player/course/$id'
      preLoaderRoute: typeof ApiPlayerCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/auth/profile': {
      id: '/api/player/auth/profile'
      path: '/profile'
      fullPath: '/api/player/auth/profile'
      preLoaderRoute: typeof ApiPlayerAuthProfileRouteImport
      parentRoute: typeof ApiPlayerAuthRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCoursesRouteChildren {
  AppCoursesCourseIdRoute: typeof AppCoursesCourseIdRoute
}

const AppCoursesRouteChildren: AppCoursesRouteChildren = {
  AppCoursesCourseIdRoute: AppCoursesCourseIdRoute,
}

const AppCoursesRouteWithChildren = AppCoursesRoute._addFileChildren(
  AppCoursesRouteChildren,
)

interface AppDownloadsRouteChildren {
  AppDownloadsPlayerRoute: typeof AppDownloadsPlayerRoute
}

const AppDownloadsRouteChildren: AppDownloadsRouteChildren = {
  AppDownloadsPlayerRoute: AppDownloadsPlayerRoute,
}

const AppDownloadsRouteWithChildren = AppDownloadsRoute._addFileChildren(
  AppDownloadsRouteChildren,
)

interface AppInstructorsRouteChildren {
  AppInstructorsInstructorIdRoute: typeof AppInstructorsInstructorIdRoute
}

const AppInstructorsRouteChildren: AppInstructorsRouteChildren = {
  AppInstructorsInstructorIdRoute: AppInstructorsInstructorIdRoute,
}

const AppInstructorsRouteWithChildren = AppInstructorsRoute._addFileChildren(
  AppInstructorsRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppCoursesRoute: typeof AppCoursesRouteWithChildren
  AppDownloadsRoute: typeof AppDownloadsRouteWithChildren
  AppExamsRoute: typeof AppExamsRoute
  AppHomeworkRoute: typeof AppHomeworkRoute
  AppInstructorsRoute: typeof AppInstructorsRouteWithChildren
  AppMyCoursesRoute: typeof AppMyCoursesRoute
  AppNotesRoute: typeof AppNotesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTermsRoute: typeof AppTermsRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLiveSessionIdRoute: typeof AppLiveSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppCoursesRoute: AppCoursesRouteWithChildren,
  AppDownloadsRoute: AppDownloadsRouteWithChildren,
  AppExamsRoute: AppExamsRoute,
  AppHomeworkRoute: AppHomeworkRoute,
  AppInstructorsRoute: AppInstructorsRouteWithChildren,
  AppMyCoursesRoute: AppMyCoursesRoute,
  AppNotesRoute: AppNotesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfileRoute: AppProfileRoute,
  AppSupportRoute: AppSupportRoute,
  AppTermsRoute: AppTermsRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppLiveSessionIdRoute: AppLiveSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminAdminsRoute: typeof SuperAdminAdminsRoute
  SuperAdminAiRoute: typeof SuperAdminAiRoute
  SuperAdminAnalyticsRoute: typeof SuperAdminAnalyticsRoute
  SuperAdminAuditLogsRoute: typeof SuperAdminAuditLogsRoute
  SuperAdminBackupRoute: typeof SuperAdminBackupRoute
  SuperAdminBrandingRoute: typeof SuperAdminBrandingRoute
  SuperAdminCoursesRoute: typeof SuperAdminCoursesRoute
  SuperAdminNotificationsRoute: typeof SuperAdminNotificationsRoute
  SuperAdminOperationsRoute: typeof SuperAdminOperationsRoute
  SuperAdminPaymentsRoute: typeof SuperAdminPaymentsRoute
  SuperAdminReportsRoute: typeof SuperAdminReportsRoute
  SuperAdminReputationRoute: typeof SuperAdminReputationRoute
  SuperAdminSecurityRoute: typeof SuperAdminSecurityRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminSimulationLogsRoute: typeof SuperAdminSimulationLogsRoute
  SuperAdminStudentsRoute: typeof SuperAdminStudentsRoute
  SuperAdminTeachersRoute: typeof SuperAdminTeachersRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAdminsRoute: SuperAdminAdminsRoute,
  SuperAdminAiRoute: SuperAdminAiRoute,
  SuperAdminAnalyticsRoute: SuperAdminAnalyticsRoute,
  SuperAdminAuditLogsRoute: SuperAdminAuditLogsRoute,
  SuperAdminBackupRoute: SuperAdminBackupRoute,
  SuperAdminBrandingRoute: SuperAdminBrandingRoute,
  SuperAdminCoursesRoute: SuperAdminCoursesRoute,
  SuperAdminNotificationsRoute: SuperAdminNotificationsRoute,
  SuperAdminOperationsRoute: SuperAdminOperationsRoute,
  SuperAdminPaymentsRoute: SuperAdminPaymentsRoute,
  SuperAdminReportsRoute: SuperAdminReportsRoute,
  SuperAdminReputationRoute: SuperAdminReputationRoute,
  SuperAdminSecurityRoute: SuperAdminSecurityRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminSimulationLogsRoute: SuperAdminSimulationLogsRoute,
  SuperAdminStudentsRoute: SuperAdminStudentsRoute,
  SuperAdminTeachersRoute: SuperAdminTeachersRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

interface TeacherRouteChildren {
  TeacherCouponsRoute: typeof TeacherCouponsRoute
  TeacherCoursesRoute: typeof TeacherCoursesRoute
  TeacherNotificationsRoute: typeof TeacherNotificationsRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherQuestionBankRoute: typeof TeacherQuestionBankRoute
  TeacherRatingsRoute: typeof TeacherRatingsRoute
  TeacherRevenueRoute: typeof TeacherRevenueRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherStatisticsRoute: typeof TeacherStatisticsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherLiveSessionIdRoute: typeof TeacherLiveSessionIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherCouponsRoute: TeacherCouponsRoute,
  TeacherCoursesRoute: TeacherCoursesRoute,
  TeacherNotificationsRoute: TeacherNotificationsRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherQuestionBankRoute: TeacherQuestionBankRoute,
  TeacherRatingsRoute: TeacherRatingsRoute,
  TeacherRevenueRoute: TeacherRevenueRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherStatisticsRoute: TeacherStatisticsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherLiveSessionIdRoute: TeacherLiveSessionIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

interface ApiPlayerAuthRouteChildren {
  ApiPlayerAuthProfileRoute: typeof ApiPlayerAuthProfileRoute
}

const ApiPlayerAuthRouteChildren: ApiPlayerAuthRouteChildren = {
  ApiPlayerAuthProfileRoute: ApiPlayerAuthProfileRoute,
}

const ApiPlayerAuthRouteWithChildren = ApiPlayerAuthRoute._addFileChildren(
  ApiPlayerAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  SupportRoute: SupportRoute,
  TeacherRoute: TeacherRouteWithChildren,
  TermsRoute: TermsRoute,
  TeacherProfileTeacherIdRoute: TeacherProfileTeacherIdRoute,
  ApiPlayerAuthRoute: ApiPlayerAuthRouteWithChildren,
  ApiPlayerCoursesRoute: ApiPlayerCoursesRoute,
  ApiPlayerGetVideoUrlRoute: ApiPlayerGetVideoUrlRoute,
  ApiPlayerLogSecurityEventRoute: ApiPlayerLogSecurityEventRoute,
  ApiPlayerProgressRoute: ApiPlayerProgressRoute,
  ApiPlayerVerifyDeviceRoute: ApiPlayerVerifyDeviceRoute,
  ApiPlayerCourseIdRoute: ApiPlayerCourseIdRoute,
  ApiPlayerOpenLessonIdRoute: ApiPlayerOpenLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
